packages:
  - "apps/*"
  - "packages/*"
catalog:
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  react-hook-form: 7.53.0
  js-cookie: 3.0.5
  xlsx: https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz
  react-aria-components: 1.4.1
  lucide-react: 0.438.0
  fflate: 0.8.2