export default function PrivacyPolicy() {
  return (
    <div className="prose mx-auto py-20">
      <h1 className="mb-8 font-bold text-3xl">Privacy Policy</h1>
      <p className="mb-4 text-gray-600">
        Last Updated: <span className="font-semibold">Oct 24, 2024</span>
      </p>

      <p className="mb-8 text-gray-800">
        Welcome to <span className="font-semibold">Extract Anything</span> (
        <span className="italic">&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;</span>). We
        operate{" "}
        <a
          href="https://extract-anything.ai"
          className="font-semibold"
          target="_blank"
          rel="noreferrer"
        >
          https://extract-anything.ai
        </a>{" "}
        (hereinafter referred to as the <span className="italic">&quot;Service&quot;</span>). This
        Privacy Policy governs your visit to{" "}
        <a
          href="https://extract-anything.ai"
          className="font-semibold"
          target="_blank"
          rel="noreferrer"
        >
          https://extract-anything.ai
        </a>{" "}
        and explains how we collect, safeguard, and disclose information resulting from your use of
        our Service.
      </p>

      <p className="mb-8 text-gray-800">
        By using our Service, you agree to the collection and use of information in accordance with
        this policy. Unless otherwise defined in this Privacy Policy, terms used have the same
        meanings as in our Terms and Conditions.
      </p>

      <h2 className="mb-4 font-semibold text-2xl">Definitions</h2>
      <ul className="mb-8">
        <li>
          <span className="font-semibold">SERVICE:</span> The{" "}
          <a
            href="https://extract-anything.ai"
            className="font-semibold"
            target="_blank"
            rel="noreferrer"
          >
            https://extract-anything.ai
          </a>{" "}
          website operated by <span className="font-semibold">Extract Anything</span>.
        </li>
        <li>
          <span className="font-semibold">PERSONAL DATA:</span> Data about a living individual who
          can be identified from those data.
        </li>
        <li>
          <span className="font-semibold">USAGE DATA:</span> Data collected automatically either
          generated by the use of Service or from Service infrastructure.
        </li>
        <li>
          <span className="font-semibold">COOKIES:</span> Small files stored on your device.
        </li>
      </ul>

      <h2 className="mb-4 font-semibold text-2xl">Information Collection and Use</h2>
      <p className="mb-8 text-gray-800">
        We collect several types of information for various purposes to provide and improve our
        Service to you.
      </p>

      <h3 className="mb-4 font-semibold text-xl">Types of Data Collected</h3>
      <h4 className="mb-4 font-semibold text-lg">Personal Data</h4>
      <p className="mb-8 text-gray-800">
        While using our Service, we may ask you to provide us with certain personally identifiable
        information, including but not limited to:
      </p>
      <ul className="mb-8">
        <li>Email address</li>
        <li>Full name</li>
        <li>Phone number</li>
        <li>Address</li>
      </ul>
      <p className="mb-8 text-gray-800">
        We may use your Personal Data to contact you with newsletters, marketing, or promotional
        materials. You may opt-out of receiving these communications by following the unsubscribe
        link or by contacting us at <span className="font-semibold">an@extract-anything.ai</span>.
      </p>

      <h4 className="mb-4 font-semibold text-lg">Usage Data</h4>
      <p className="mb-8 text-gray-800">
        We may also collect information that your browser sends whenever you visit our Service or
        when you access Service via a mobile device. This Usage Data may include:
      </p>
      <ul className="mb-8">
        <li>Your computer&apos;s IP address</li>
        <li>Browser type and version</li>
        <li>Pages of our Service that you visit</li>
        <li>Time and date of your visit</li>
        <li>Time spent on those pages</li>
      </ul>

      <h4 className="mb-4 font-semibold text-lg">Tracking Cookies Data</h4>
      <p className="mb-8 text-gray-800">
        We use cookies and similar tracking technologies to track activity on our Service. You can
        instruct your browser to refuse all cookies or to indicate when a cookie is being sent.
        However, if you do not accept cookies, you may not be able to use some portions of our
        Service.
      </p>

      <h3 className="mb-4 font-semibold text-xl">Use of Data</h3>
      <p className="mb-8 text-gray-800">
        <span className="font-semibold">Extract Anything</span> uses the collected data for various
        purposes:
      </p>
      <ul className="mb-8">
        <li>To provide and maintain our Service</li>
        <li>To notify you about changes to our Service</li>
        <li>To allow you to participate in interactive features when you choose</li>
        <li>To provide customer support</li>
        <li>To gather analysis or valuable information so that we can improve our Service</li>
        <li>To monitor the usage of our Service</li>
        <li>To detect, prevent, and address technical issues</li>
        <li>To fulfill any other purpose for which you provide it</li>
        <li>
          To carry out our obligations and enforce our rights arising from any contracts entered
          into between you and us
        </li>
        <li>
          To provide you with news, special offers, and general information about other goods,
          services, and events which we offer that are similar to those that you have already
          purchased or enquired about unless you have opted not to receive such information
        </li>
      </ul>

      <h3 className="mb-4 font-semibold text-xl">Retention of Data</h3>
      <p className="mb-8 text-gray-800">
        We will retain your Personal Data only for as long as necessary for the purposes set out in
        this Privacy Policy. We will retain and use your Personal Data to the extent necessary to
        comply with our legal obligations, resolve disputes, and enforce our legal agreements and
        policies.
      </p>

      <h3 className="mb-4 font-semibold text-xl">Transfer of Data</h3>
      <p className="mb-8 text-gray-800">
        Your information, including Personal Data, may be transferred to – and maintained on –
        computers located outside of your state, province, country, or other governmental
        jurisdiction where the data protection laws may differ from those of your jurisdiction. Your
        consent to this Privacy Policy followed by your submission of such information represents
        your agreement to that transfer.
      </p>

      <h3 className="mb-4 font-semibold text-xl">Disclosure of Data</h3>
      <p className="mb-8 text-gray-800">
        We may disclose personal information that we collect, or you provide:
      </p>
      <ul className="mb-8">
        <li>
          <span className="font-semibold">For Law Enforcement:</span> Under certain circumstances,
          we may be required to disclose your Personal Data if required to do so by law or in
          response to valid requests by public authorities.
        </li>
        <li>
          <span className="font-semibold">Business Transaction:</span> If we or our subsidiaries are
          involved in a merger, acquisition, or asset sale, your Personal Data may be transferred.
        </li>
        <li>
          <span className="font-semibold">Other Cases:</span> We may disclose your information:
          <ul className="ml-6">
            <li>
              To contractors, service providers, and other third parties we use to support our
              business
            </li>
            <li>To fulfill the purpose for which you provide it</li>
            <li>With your consent in other cases</li>
            <li>
              If we believe disclosure is necessary or appropriate to protect the rights, property,
              or safety of the Company, our customers, or others
            </li>
          </ul>
        </li>
      </ul>

      <h3 className="mb-4 font-semibold text-xl">Security of Data</h3>
      <p className="mb-8 text-gray-800">
        The security of your data is important to us but remember that no method of transmission
        over the Internet or method of electronic storage is 100% secure. While we strive to use
        commercially acceptable means to protect your Personal Data, we cannot guarantee its
        absolute security.
      </p>

      <h3 className="mb-4 font-semibold text-xl">Your Data Protection Rights</h3>
      <p className="mb-8 text-gray-800">
        Depending on your location, you may have the following data protection rights:
      </p>
      <ul className="mb-8">
        <li>
          <span className="font-semibold">Right to Access:</span> You have the right to access the
          personal information we hold about you.
        </li>
        <li>
          <span className="font-semibold">Right to Rectification:</span> You have the right to
          request the correction of inaccurate personal information.
        </li>
        <li>
          <span className="font-semibold">Right to Erasure:</span> You have the right to request the
          deletion of your personal data.
        </li>
        <li>
          <span className="font-semibold">Right to Restriction of Processing:</span> You have the
          right to request the restriction of processing your personal information.
        </li>
        <li>
          <span className="font-semibold">Right to Data Portability:</span> You have the right to
          receive your personal data in a structured, commonly used, and machine-readable format.
        </li>
        <li>
          <span className="font-semibold">Right to Withdraw Consent:</span> You have the right to
          withdraw consent at any time where we rely on your consent to process your personal
          information.
        </li>
      </ul>
      <p className="mb-8 text-gray-800">
        To exercise any of these rights, please contact us at{" "}
        <span className="font-semibold">an@extract-anything.ai</span>. We may ask you to verify your
        identity before responding to such requests.
      </p>

      <h3 className="mb-4 font-semibold text-xl">Children&apos;s Privacy</h3>
      <p className="mb-8 text-gray-800">
        Our Service is not intended for use by children under the age of 18. We do not knowingly
        collect personally identifiable information from children under 18. If you become aware that
        a child has provided us with Personal Data, please contact us. If we become aware that we
        have collected Personal Data from children without verification of parental consent, we take
        steps to remove that information from our servers.
      </p>

      <h3 className="mb-4 font-semibold text-xl">Changes to This Privacy Policy</h3>
      <p className="mb-8 text-gray-800">
        We may update our Privacy Policy from time to time. We will notify you of any changes by
        posting the new Privacy Policy on this page. We will let you know via email and/or a
        prominent notice on our Service, prior to the change becoming effective and update the{" "}
        <span className="italic">&quot;Last Updated&quot;</span> date at the top of this Privacy
        Policy.
      </p>
      <p className="mb-8 text-gray-800">
        You are advised to review this Privacy Policy periodically for any changes. Changes to this
        Privacy Policy are effective when they are posted on this page.
      </p>

      <h3 className="mb-4 font-semibold text-xl">Contact Us</h3>
      <p className="text-gray-800">
        If you have any questions about this Privacy Policy, please contact us at:{" "}
        <span className="font-semibold">an@extract-anything.ai</span>.
      </p>
    </div>
  )
}
